################################################################################
#
# #OWNER# ___PROJECTNAME___
# Copyright (c) ___YEAR___ #OWNER#
# All Rights Reserved Worldwide
# Proprietary and Confidential - Not for Distribution
# Written by #AUTHOR#
#
# ___FILENAME___
#
#
# AUTHOR IDENTITY:
#    ___FULLUSERNAME___		___DATE___
#    
################################################################################

